# Generated by Django 2.2.4 on 2019-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='documents/CVs/')),
                ('applying_for', models.CharField(max_length=150)),
                ('cover_letter', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
