# Generated by Django 2.2.4 on 2019-09-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_career_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='uploaded',
        ),
    ]
