# Generated by Django 2.2.4 on 2019-10-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_jobdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
