# Generated by Django 2.2.4 on 2019-10-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_jobdescription_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='remove',
            field=models.BooleanField(default=False),
        ),
    ]
