# Generated by Django 2.2.4 on 2019-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdescription',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
