# Generated by Django 2.2.4 on 2019-09-15 17:03

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190915_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=config.utils.upload_image_path_posts),
        ),
    ]
