# Generated by Django 2.2.4 on 2019-09-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='Welcome to Finetouch', max_length=100),
            preserve_default=False,
        ),
    ]
