# Generated by Django 2.2.4 on 2019-09-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190918_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, help_text='model type(for generators)', max_length=100, null=True),
        ),
    ]
