# Generated by Django 2.2.4 on 2019-09-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190920_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='automatic',
        ),
        migrations.AddField(
            model_name='product',
            name='automatic_or_manual',
            field=models.CharField(blank=True, help_text='manual or automatic', max_length=40, null=True),
        ),
    ]
