# Generated by Django 2.2.4 on 2019-09-26 14:28

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190920_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, help_text='type of the product', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='content', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=config.utils.upload_image_path_products),
        ),
    ]
