# Generated by Django 2.2.4 on 2019-09-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190928_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='outlet_inlet',
            new_name='inlet',
        ),
        migrations.AddField(
            model_name='product',
            name='flow_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='outlet',
            field=models.CharField(blank=True, help_text='eg 2', max_length=40, null=True),
        ),
    ]
