# Generated by Django 2.2.4 on 2019-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rpm',
            field=models.CharField(blank=True, help_text="eg '2850rpm'", max_length=40, null=True),
        ),
    ]
