# Generated by Django 2.2.4 on 2019-09-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
