# Generated by Django 2.2.4 on 2019-09-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Categories'},
        ),
    ]
